#!/usr/bin/env python
#
# MCC 118 example program
# Read and display analog input values
#

import sys
import time
import matplotlib.pyplot as plt
from daqhats import hat_list, HatIDs, mcc118

# get hat list of MCC daqhat boards
board_list = hat_list(filter_by_id = HatIDs.ANY)
if not board_list:
    print("No boards found")
    sys.exit()

# Initialize variables
sampling_frequency = 1000  # in Hz
sampling_interval = 1 / sampling_frequency
num_samples = 15000  # 15 seconds of data
x_values = [i * sampling_interval for i in range(num_samples)]
y_values = [[] for _ in range(board_list[0].info().NUM_AI_CHANNELS)]  # create a list for each channel

# Read data from each channel
for entry in board_list:
    if entry.id == HatIDs.MCC_118:
        print("Board {}: MCC 118".format(entry.address))
        board = mcc118(entry.address)
        for channel in range(board.info().NUM_AI_CHANNELS):
            for i in range(num_samples):
                value = board.a_in_read(channel)
                y_values[channel].append(value)
                time.sleep(sampling_interval)

# Plot data for each channel
for channel, data in enumerate(y_values):
    plt.plot(x_values, data, label=f"Ch {channel}")

plt.legend()
plt.xlabel("Time (s)")
plt.ylabel("Voltage (V)")
plt.title("Analog Input Channels")
plt.show()
